# Generated by Django 2.2.11 on 2020-04-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200403_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Menu', verbose_name='权限菜单'),
            preserve_default=False,
        ),
    ]
