# Generated by Django 2.2.11 on 2020-04-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200407_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='组名称')),
            ],
            options={
                'verbose_name_plural': '权限组',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': '权限表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default=0, max_length=16, verbose_name='权限码'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu_gp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='rbac.Permission', verbose_name='默认选中的组内权限ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单标题'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, verbose_name='含正则的URL'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='角色关联的权限'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='角色名称'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户关联的角色'),
        ),
        migrations.AddField(
            model_name='group',
            name='menu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='关联的菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='所属组'),
        ),
    ]
